import fs from 'node:fs';
import { ipcMain } from 'electron';
import { IPC } from '../../../shared/ipc-channels';
import { SessionRepository } from '../../db/repositories/session-repository';
import { WorktreeManager, isAutoGeneratedBranch } from '../../git/worktree-manager';
import { getProjectDb } from '../../db/database';
import {
  getProjectRepos,
  buildAutoCommandVars,
  ensureTaskWorktree,
  ensureTaskBranchCheckout,
  createTransitionEngine,
  cleanupTaskResources,
  spawnAgent,
} from '../helpers';
import { guardActiveNonWorktreeSessions } from './task-move';
import { interpolateTemplate } from '../../agent/shared';
import { withTaskLock } from '../task-lifecycle-lock';
import type { IpcContext } from '../ipc-context';

export function registerTaskCrudHandlers(context: IpcContext): void {
  ipcMain.handle(IPC.TASK_LIST, (_, swimlaneId?) => {
    const { tasks } = getProjectRepos(context);
    return tasks.list(swimlaneId);
  });

  ipcMain.handle(IPC.TASK_CREATE, async (_, input) => {
    const { tasks, swimlanes, actions, attachments } = getProjectRepos(context);
    const { pendingAttachments, ...taskInput } = input;
    const task = tasks.create(taskInput);

    // Save any pending attachments from the dialog
    if (pendingAttachments?.length && context.currentProjectPath) {
      for (const att of pendingAttachments) {
        attachments.add(context.currentProjectPath, task.id, att.filename, att.data, att.media_type);
      }
    }

    // Auto-spawn: if target column has auto_spawn, start the agent
    const toLane = swimlanes.getById(task.swimlane_id);
    if (toLane?.auto_spawn && context.currentProjectPath && context.currentProjectId) {
      const projectPath = context.currentProjectPath;
      const projectId = context.currentProjectId;
      // Serialize the spawn flow against any concurrent lifecycle op (move,
      // suspend, kill, etc.) for the freshly created task.
      await withTaskLock(task.id, async () => {
        try {
          await ensureTaskWorktree(context, task, tasks, projectPath);
        } catch (worktreeError) {
          console.error('[TASK_CREATE] Worktree creation failed:', worktreeError);
          return;
        }

        // Checkout the task's branch in the main repo (non-worktree tasks only).
        // If checkout fails, the task is still created but no agent is spawned.
        try {
          guardActiveNonWorktreeSessions(context, task, tasks);
          await ensureTaskBranchCheckout(task, projectPath);
        } catch (checkoutError) {
          console.error('[TASK_CREATE] Branch checkout failed:', checkoutError);
          return;
        }

        const db = getProjectDb(projectId);
        const sessionRepo = new SessionRepository(db);
        const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachments, projectId, projectPath);

        try {
          // Use '*' as fromSwimlaneId -- no source column on creation, matches wildcard transitions
          await engine.executeTransition(task, '*', toLane.id, toLane.permission_mode);
        } catch (err) {
          console.error('[TASK_CREATE] Transition engine error:', err);
        }

        // Re-read task; if still no session, resume suspended or spawn fresh
        let finalTask = tasks.getById(task.id);
        if (finalTask && !finalTask.session_id && toLane.auto_spawn) {
          console.log(`[TASK_CREATE] Ensuring agent for task ${task.id.slice(0, 8)}`);
          try {
            await engine.resumeSuspendedSession(finalTask, toLane.permission_mode);
            finalTask = tasks.getById(task.id);
          } catch (err) {
            console.error('[TASK_CREATE] Failed to start session:', err);
          }
        }

        // Schedule auto-command for freshly spawned session
        if (finalTask?.session_id && toLane.auto_command) {
          const vars = buildAutoCommandVars(finalTask);
          const interpolated = interpolateTemplate(toLane.auto_command, vars);
          context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
        }
      });
    }

    return tasks.getById(task.id) ?? task;
  });

  ipcMain.handle(IPC.TASK_UPDATE, async (_, input) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks } = getProjectRepos(context, resolvedProjectId);
    const existing = tasks.getById(input.id);

    // If title changed and task has a worktree branch, try to rename the branch
    if (input.title && existing?.branch_name && existing?.worktree_path
        && isAutoGeneratedBranch(existing.branch_name, existing.id, existing.title)
        && input.title !== existing.title && resolvedProjectPath
        && !existing.pr_url) {
      // Guard: skip if the agent is actively thinking (git operations may be in flight)
      const taskSession = context.sessionManager.listSessions()
        .find(s => s.taskId === input.id && (s.status === 'running' || s.status === 'queued'));
      const activityCache = context.sessionManager.getActivityCache();
      const isThinking = taskSession && activityCache[taskSession.id] === 'thinking';

      if (isThinking) {
        console.log(`[TASK_UPDATE] Skipping branch rename -- task ${input.id.slice(0, 8)} agent is thinking`);
      } else if (!fs.existsSync(existing.worktree_path)) {
        console.log(`[TASK_UPDATE] Skipping branch rename -- worktree path missing: ${existing.worktree_path}`);
      } else {
        const worktreeManager = new WorktreeManager(resolvedProjectPath);
        const effectiveConfig = context.configManager.getEffectiveConfig(resolvedProjectPath);
        const boardDefaultBranch = context.boardConfigManager.getDefaultBaseBranch();
        const defaultBaseBranch = boardDefaultBranch || effectiveConfig.git.defaultBaseBranch || 'main';
        const newBranchName = await worktreeManager.withLock(() =>
          worktreeManager.renameBranch(input.id, existing.branch_name!, input.title, {
            baseBranch: existing.base_branch,
            defaultBaseBranch,
          }),
        );
        if (newBranchName) {
          console.log(`[TASK_UPDATE] Branch renamed: ${existing.branch_name} -> ${newBranchName}`);
          input.branch_name = newBranchName;
        } else {
          console.log(`[TASK_UPDATE] Branch rename skipped (same slug or failed) for ${existing.branch_name}`);
        }
      }
    }

    return tasks.update(input);
  });

  ipcMain.handle(IPC.TASK_DELETE, (_, id) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    // Serialize against any in-flight session lifecycle op so we don't kill
    // a PTY mid-spawn or delete the task while a resume is creating a worktree.
    return withTaskLock(id, async () => {
      const task = tasks.getById(id);
      if (task) {
        attachments.deleteByTaskId(id);
        await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
      }
      tasks.delete(id);
    });
  });

  ipcMain.handle(IPC.TASK_LIST_ARCHIVED, () => {
    const { tasks } = getProjectRepos(context);
    return tasks.listArchived();
  });

  ipcMain.handle(IPC.TASK_UNARCHIVE, (_, input: { id: string; targetSwimlaneId: string }) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    if (!resolvedProjectId) throw new Error('No project is currently open');

    const { tasks, swimlanes, actions, attachments: attachmentRepo } = getProjectRepos(context, resolvedProjectId);

    // Serialize the unarchive + spawn flow against any other lifecycle op for
    // the same task. Unarchive itself is sync DB work; the lock primarily
    // covers the worktree/checkout/spawn awaits below.
    return withTaskLock(input.id, async () => {
      // Determine position at end of target lane
      const laneTasks = tasks.list(input.targetSwimlaneId);
      const position = laneTasks.length;

      const task = tasks.unarchive(input.id, input.targetSwimlaneId, position);

      const toLane = swimlanes.getById(input.targetSwimlaneId);

      // Guard: don't resume if target doesn't auto-spawn (backlog, done, or custom with auto_spawn=false)
      if (!toLane?.auto_spawn) {
        return tasks.getById(input.id);
      }

      // Create worktree if needed (any non-backlog column gets an agent)
      try {
        await ensureTaskWorktree(context, task, tasks, resolvedProjectPath);
      } catch (worktreeError) {
        console.error('[TASK_UNARCHIVE] Worktree creation failed:', worktreeError);
        return tasks.getById(input.id);
      }

      // Checkout the task's branch in the main repo (non-worktree tasks only).
      // If checkout fails, the task is still unarchived but no agent is spawned.
      try {
        guardActiveNonWorktreeSessions(context, task, tasks);
        await ensureTaskBranchCheckout(task, resolvedProjectPath);
      } catch (checkoutError) {
        console.error('[TASK_UNARCHIVE] Branch checkout failed:', checkoutError);
        return tasks.getById(input.id);
      }

      // Execute transition actions + resume suspended session (or spawn fresh).
      // Uses the consolidated spawnAgent helper which handles:
      // - user-paused guard (won't auto-resume manually paused tasks)
      // - correct auto_command handling (resume prompt vs commandInjector)
      // - single source of truth for spawn/resume logic
      if (resolvedProjectPath && toLane) {
        const doneLane = swimlanes.list().find((lane) => lane.role === 'done');
        if (doneLane) {
          const db = getProjectDb(resolvedProjectId);
          const sessionRepo = new SessionRepository(db);
          const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachmentRepo, resolvedProjectId, resolvedProjectPath);

          await spawnAgent({ context, engine, tasks, sessionRepo, task, fromSwimlaneId: doneLane.id, toLane, skipPromptTemplate: true });
        }
      }

      return tasks.getById(input.id);
    });
  });

  ipcMain.handle(IPC.TASK_BULK_DELETE, async (_, ids: string[]) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    for (const id of ids) {
      // Per-task lock so each delete serializes against any in-flight session
      // op for that task, while different tasks remain independent.
      await withTaskLock(id, async () => {
        const task = tasks.getById(id);
        if (task) {
          attachments.deleteByTaskId(id);
          await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
        }
        tasks.delete(id);
      });
    }
  });

  ipcMain.handle(IPC.TASK_BULK_UNARCHIVE, async (_, ids: string[], targetSwimlaneId: string) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    if (!resolvedProjectId) throw new Error('No project is currently open');

    const { tasks, swimlanes, actions, attachments: attachmentRepo } = getProjectRepos(context, resolvedProjectId);
    const toLane = swimlanes.getById(targetSwimlaneId);

    for (const id of ids) {
      // Per-task lock so each unarchive+spawn serializes against any in-flight
      // session op for that task, while different tasks remain independent.
      await withTaskLock(id, async () => {
        const laneTasks = tasks.list(targetSwimlaneId);
        const position = laneTasks.length;
        const task = tasks.unarchive(id, targetSwimlaneId, position);

        if (!toLane?.auto_spawn) return;

        try {
          await ensureTaskWorktree(context, task, tasks, resolvedProjectPath);
        } catch (worktreeError) {
          console.error(`[TASK_BULK_UNARCHIVE] Worktree creation failed for task ${id.slice(0, 8)}:`, worktreeError);
          return;
        }

        // Checkout the task's branch in the main repo (non-worktree tasks only).
        // Catch per-task so one failure doesn't block the entire batch.
        try {
          guardActiveNonWorktreeSessions(context, task, tasks);
          await ensureTaskBranchCheckout(task, resolvedProjectPath);
        } catch (checkoutError) {
          console.error(`[TASK_BULK_UNARCHIVE] Branch checkout failed for task ${id.slice(0, 8)}:`, checkoutError);
          return;
        }

        if (resolvedProjectPath && toLane) {
          const doneLane = swimlanes.list().find((lane) => lane.role === 'done');
          if (doneLane) {
            const db = getProjectDb(resolvedProjectId);
            const sessionRepo = new SessionRepository(db);
            const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachmentRepo, resolvedProjectId, resolvedProjectPath);

            await spawnAgent({ context, engine, tasks, sessionRepo, task, fromSwimlaneId: doneLane.id, toLane, skipPromptTemplate: true });
          }
        }
      });
    }
  });
}
