import fs from 'node:fs';
import { ipcMain } from 'electron';
import { simpleGit } from 'simple-git';
import { IPC } from '../../../shared/ipc-channels';
import { SessionRepository } from '../../db/repositories/session-repository';
import { WorktreeManager, isAutoGeneratedBranch } from '../../git/worktree-manager';
import { getProjectDb } from '../../db/database';
import {
  getProjectRepos,
  buildAutoCommandVars,
  ensureTaskWorktree,
  ensureTaskBranchCheckout,
  createTransitionEngine,
  cleanupTaskResources,
} from '../helpers';
import { handleTaskMove, guardActiveNonWorktreeSessions } from './task-move';
import { carryUncommittedChanges } from './task-branch';
import { interpolateTemplate } from '../../agent/shared';
import { withTaskLock } from '../task-lifecycle-lock';
import type { IpcContext } from '../ipc-context';
import type { TaskSwitchBranchInput } from '../../../shared/types';

// Re-export for backward compatibility (tests import from this module)
export { carryUncommittedChanges } from './task-branch';
export type { CarryResult } from './task-branch';
export { handleTaskMove } from './task-move';
export { guardActiveNonWorktreeSessions } from './task-move';

export function registerTaskHandlers(context: IpcContext): void {
  ipcMain.handle(IPC.TASK_LIST, (_, swimlaneId?) => {
    const { tasks } = getProjectRepos(context);
    return tasks.list(swimlaneId);
  });

  ipcMain.handle(IPC.TASK_CREATE, async (_, input) => {
    const { tasks, swimlanes, actions, attachments } = getProjectRepos(context);
    const { pendingAttachments, ...taskInput } = input;
    const task = tasks.create(taskInput);

    // Save any pending attachments from the dialog
    if (pendingAttachments?.length && context.currentProjectPath) {
      for (const att of pendingAttachments) {
        attachments.add(context.currentProjectPath, task.id, att.filename, att.data, att.media_type);
      }
    }

    // Auto-spawn: if target column has auto_spawn, start the agent
    const toLane = swimlanes.getById(task.swimlane_id);
    if (toLane?.auto_spawn && context.currentProjectPath && context.currentProjectId) {
      try {
        await ensureTaskWorktree(context, task, tasks, context.currentProjectPath);
      } catch (worktreeError) {
        console.error('[TASK_CREATE] Worktree creation failed:', worktreeError);
        return tasks.getById(task.id) ?? task;
      }

      // Checkout the task's branch in the main repo (non-worktree tasks only).
      // If checkout fails, the task is still created but no agent is spawned.
      try {
        guardActiveNonWorktreeSessions(context, task, tasks);
        await ensureTaskBranchCheckout(task, context.currentProjectPath);
      } catch (checkoutError) {
        console.error('[TASK_CREATE] Branch checkout failed:', checkoutError);
        return tasks.getById(task.id) ?? task;
      }

      const db = getProjectDb(context.currentProjectId);
      const sessionRepo = new SessionRepository(db);
      const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachments, context.currentProjectId, context.currentProjectPath);

      try {
        // Use '*' as fromSwimlaneId - no source column on creation, matches wildcard transitions
        await engine.executeTransition(task, '*', toLane.id, toLane.permission_mode);
      } catch (err) {
        console.error('[TASK_CREATE] Transition engine error:', err);
      }

      // Re-read task; if still no session, resume suspended or spawn fresh
      let finalTask = tasks.getById(task.id);
      if (finalTask && !finalTask.session_id && toLane.auto_spawn) {
        console.log(`[TASK_CREATE] Ensuring agent for task ${task.id.slice(0, 8)}`);
        try {
          await engine.resumeSuspendedSession(finalTask, toLane.permission_mode);
          finalTask = tasks.getById(task.id);
        } catch (err) {
          console.error('[TASK_CREATE] Failed to start session:', err);
        }
      }

      // Schedule auto-command for freshly spawned session
      if (finalTask?.session_id && toLane.auto_command) {
        const vars = buildAutoCommandVars(finalTask);
        const interpolated = interpolateTemplate(toLane.auto_command, vars);
        context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
      }
    }

    return tasks.getById(task.id) ?? task;
  });

  ipcMain.handle(IPC.TASK_UPDATE, async (_, input) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks } = getProjectRepos(context, resolvedProjectId);
    const existing = tasks.getById(input.id);

    // If title changed and task has a worktree branch, try to rename the branch
    if (input.title && existing?.branch_name && existing?.worktree_path
        && isAutoGeneratedBranch(existing.branch_name, existing.id, existing.title)
        && input.title !== existing.title && resolvedProjectPath
        && !existing.pr_url) {
      // Guard: skip if the agent is actively thinking (git operations may be in flight)
      const taskSession = context.sessionManager.listSessions()
        .find(s => s.taskId === input.id && (s.status === 'running' || s.status === 'queued'));
      const activityCache = context.sessionManager.getActivityCache();
      const isThinking = taskSession && activityCache[taskSession.id] === 'thinking';

      if (isThinking) {
        console.log(`[TASK_UPDATE] Skipping branch rename - task ${input.id.slice(0, 8)} agent is thinking`);
      } else if (!fs.existsSync(existing.worktree_path)) {
        console.log(`[TASK_UPDATE] Skipping branch rename - worktree path missing: ${existing.worktree_path}`);
      } else {
        const worktreeManager = new WorktreeManager(resolvedProjectPath);
        const effectiveConfig = context.configManager.getEffectiveConfig(resolvedProjectPath);
        const boardDefaultBranch = context.boardConfigManager.getDefaultBaseBranch();
        const defaultBaseBranch = boardDefaultBranch || effectiveConfig.git.defaultBaseBranch || 'main';
        const newBranchName = await worktreeManager.withLock(() =>
          worktreeManager.renameBranch(input.id, existing.branch_name!, input.title, {
            baseBranch: existing.base_branch,
            defaultBaseBranch,
          }),
        );
        if (newBranchName) {
          console.log(`[TASK_UPDATE] Branch renamed: ${existing.branch_name} -> ${newBranchName}`);
          input.branch_name = newBranchName;
        } else {
          console.log(`[TASK_UPDATE] Branch rename skipped (same slug or failed) for ${existing.branch_name}`);
        }
      }
    }

    return tasks.update(input);
  });

  ipcMain.handle(IPC.TASK_DELETE, async (_, id) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    // Serialize against any in-flight session lifecycle op for this task so
    // the long awaits inside cleanup don't race with spawn/resume/etc.
    await withTaskLock(id, async () => {
      const task = tasks.getById(id);
      if (task) {
        attachments.deleteByTaskId(id);
        await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
      }
      tasks.delete(id);
    });
  });

  ipcMain.handle(IPC.TASK_MOVE, async (_, input) => handleTaskMove(context, input));

  ipcMain.handle(IPC.TASK_LIST_ARCHIVED, () => {
    const { tasks } = getProjectRepos(context);
    return tasks.listArchived();
  });

  ipcMain.handle(IPC.TASK_UNARCHIVE, async (_, input: { id: string; targetSwimlaneId: string }) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    if (!resolvedProjectId) throw new Error('No project is currently open');

    const { tasks, swimlanes, actions, attachments: attachmentRepo } = getProjectRepos(context, resolvedProjectId);

    // Determine position at end of target lane
    const laneTasks = tasks.list(input.targetSwimlaneId);
    const position = laneTasks.length;

    const task = tasks.unarchive(input.id, input.targetSwimlaneId, position);

    const toLane = swimlanes.getById(input.targetSwimlaneId);

    // Guard: don't resume if target doesn't auto-spawn (backlog, done, or custom with auto_spawn=false)
    if (!toLane?.auto_spawn) {
      return tasks.getById(input.id);
    }

    // Create worktree if needed (any non-backlog column gets an agent)
    try {
      await ensureTaskWorktree(context, task, tasks, resolvedProjectPath);
    } catch (worktreeError) {
      console.error('[TASK_UNARCHIVE] Worktree creation failed:', worktreeError);
      return tasks.getById(input.id);
    }

    // Checkout the task's branch in the main repo (non-worktree tasks only).
    // If checkout fails, the task is still unarchived but no agent is spawned.
    try {
      guardActiveNonWorktreeSessions(context, task, tasks);
      await ensureTaskBranchCheckout(task, resolvedProjectPath);
    } catch (checkoutError) {
      console.error('[TASK_UNARCHIVE] Branch checkout failed:', checkoutError);
      return tasks.getById(input.id);
    }

    // Execute transition actions (from Done -> target) for ALL non-kill columns
    if (resolvedProjectPath) {
      const doneLane = swimlanes.list().find((l) => l.role === 'done');
      if (doneLane) {
        const db = getProjectDb(resolvedProjectId);
        const sessionRepo = new SessionRepository(db);
        const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachmentRepo, resolvedProjectId, resolvedProjectPath);

        try {
          await engine.executeTransition(task, doneLane.id, input.targetSwimlaneId, toLane?.permission_mode, true);
        } catch (err) {
          console.error('[TASK_UNARCHIVE] Transition engine error:', err);
        }

        // Re-read task; if still no session, resume suspended or spawn fresh.
        let finalTask = tasks.getById(task.id);
        if (finalTask && !finalTask.session_id && toLane?.auto_spawn) {
          console.log(`[TASK_UNARCHIVE] Ensuring agent for task ${task.id.slice(0, 8)}`);
          try {
            await engine.resumeSuspendedSession(finalTask, toLane.permission_mode, true);
            finalTask = tasks.getById(task.id);
          } catch (err) {
            console.error('[TASK_UNARCHIVE] Failed to start session:', err);
          }
        }

        // Schedule auto-command for freshly spawned session
        if (finalTask?.session_id && toLane?.auto_command) {
          const vars = buildAutoCommandVars(finalTask);
          const interpolated = interpolateTemplate(toLane.auto_command, vars);
          context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
        }
      }
    }

    return tasks.getById(input.id);
  });

  ipcMain.handle(IPC.TASK_BULK_DELETE, async (_, ids: string[]) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    const failures: Array<{ id: string; error: string }> = [];
    for (const id of ids) {
      try {
        // Per-task lock so each delete serializes against any in-flight
        // session op for that task while different tasks stay independent.
        await withTaskLock(id, async () => {
          const task = tasks.getById(id);
          if (task) {
            attachments.deleteByTaskId(id);
            await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
          }
          tasks.delete(id);
        });
      } catch (error) {
        // One failure should not abort the whole batch. Collect and report
        // aggregate at the end.
        const message = error instanceof Error ? error.message : String(error);
        console.error(`[TASK_BULK_DELETE] Failed for task ${id.slice(0, 8)}:`, error);
        failures.push({ id, error: message });
      }
    }
    if (failures.length > 0) {
      throw new Error(
        `Bulk delete completed with ${failures.length} failure${failures.length === 1 ? '' : 's'}: `
        + failures.map((failure) => `${failure.id.slice(0, 8)} (${failure.error})`).join(', '),
      );
    }
  });

  ipcMain.handle(IPC.TASK_BULK_UNARCHIVE, async (_, ids: string[], targetSwimlaneId: string) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    if (!resolvedProjectId) throw new Error('No project is currently open');

    const { tasks, swimlanes, actions, attachments: attachmentRepo } = getProjectRepos(context, resolvedProjectId);
    const toLane = swimlanes.getById(targetSwimlaneId);

    for (const id of ids) {
      const laneTasks = tasks.list(targetSwimlaneId);
      const position = laneTasks.length;
      const task = tasks.unarchive(id, targetSwimlaneId, position);

      if (!toLane?.auto_spawn) continue;

      try {
        await ensureTaskWorktree(context, task, tasks, resolvedProjectPath);
      } catch (worktreeError) {
        console.error(`[TASK_BULK_UNARCHIVE] Worktree creation failed for task ${id.slice(0, 8)}:`, worktreeError);
        continue;
      }

      // Checkout the task's branch in the main repo (non-worktree tasks only).
      // Catch per-task so one failure doesn't block the entire batch.
      try {
        guardActiveNonWorktreeSessions(context, task, tasks);
        await ensureTaskBranchCheckout(task, resolvedProjectPath);
      } catch (checkoutError) {
        console.error(`[TASK_BULK_UNARCHIVE] Branch checkout failed for task ${id.slice(0, 8)}:`, checkoutError);
        continue;
      }

      if (resolvedProjectPath) {
        const doneLane = swimlanes.list().find((lane) => lane.role === 'done');
        if (doneLane) {
          const db = getProjectDb(resolvedProjectId);
          const sessionRepo = new SessionRepository(db);
          const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachmentRepo, resolvedProjectId, resolvedProjectPath);

          try {
            await engine.executeTransition(task, doneLane.id, targetSwimlaneId, toLane?.permission_mode, true);
          } catch (error) {
            console.error('[TASK_BULK_UNARCHIVE] Transition engine error:', error);
          }

          let finalTask = tasks.getById(task.id);
          if (finalTask && !finalTask.session_id && toLane?.auto_spawn) {
            try {
              await engine.resumeSuspendedSession(finalTask, toLane.permission_mode, true);
              finalTask = tasks.getById(task.id);
            } catch (error) {
              console.error('[TASK_BULK_UNARCHIVE] Failed to start session:', error);
            }
          }

          if (finalTask?.session_id && toLane?.auto_command) {
            const vars = buildAutoCommandVars(finalTask);
            const interpolated = interpolateTemplate(toLane.auto_command, vars);
            context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
          }
        }
      }
    }
  });

  ipcMain.handle(IPC.TASK_SWITCH_BRANCH, async (_, input: TaskSwitchBranchInput) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    if (!resolvedProjectId) throw new Error('No project is currently open');

    const { tasks } = getProjectRepos(context, resolvedProjectId);
    const task = tasks.getById(input.taskId);
    if (!task) throw new Error(`Task ${input.taskId} not found`);

    // Guard: must not have a running PTY session
    if (task.session_id) {
      const activeSession = context.sessionManager.listSessions()
        .find(s => s.id === task.session_id && (s.status === 'running' || s.status === 'queued'));
      if (activeSession) {
        throw new Error('Cannot switch branch while a session is running. Suspend the session first.');
      }
    }

    const db = getProjectDb(resolvedProjectId);
    const sessionRepo = new SessionRepository(db);

    if (input.enableWorktree && !task.worktree_path) {
      // --- Path B: Enable worktree ---
      if (!resolvedProjectPath) throw new Error('No project path available');

      // Update base branch and use_worktree before creating the worktree
      tasks.update({
        id: task.id,
        base_branch: input.newBaseBranch || null,
        use_worktree: 1,
      });
      Object.assign(task, tasks.getById(task.id));

      // Create the worktree
      await ensureTaskWorktree(context, task, tasks, resolvedProjectPath);
      const updatedTask = tasks.getById(task.id);
      if (!updatedTask?.worktree_path) {
        throw new Error('Failed to create worktree');
      }

      // Best-effort: carry uncommitted changes from main repo to worktree
      try {
        const carryResult = await carryUncommittedChanges(
          resolvedProjectPath, updatedTask.worktree_path, task.id.slice(0, 8),
        );
        if (carryResult.carriedTracked || carryResult.carriedUntracked.length > 0) {
          console.log(`[TASK_SWITCH_BRANCH] Carried uncommitted changes to worktree (tracked: ${carryResult.carriedTracked}, untracked: ${carryResult.carriedUntracked.length})`);
        }
        if (carryResult.applyFailed) {
          console.warn(`[TASK_SWITCH_BRANCH] Could not apply tracked changes to worktree. They remain in the main repo.`);
        }
        if (carryResult.failedUntracked.length > 0) {
          console.warn(`[TASK_SWITCH_BRANCH] Could not copy ${carryResult.failedUntracked.length} untracked file(s) to worktree.`);
        }
      } catch {
        // Best-effort, non-fatal
      }

      // Update session record CWD for seamless resume
      const latestRecord = sessionRepo.getLatestForTask(task.id);
      if (latestRecord && latestRecord.status === 'suspended') {
        sessionRepo.updateCwd(latestRecord.id, updatedTask.worktree_path);
        console.log(`[TASK_SWITCH_BRANCH] Updated session ${latestRecord.id.slice(0, 8)} CWD to worktree`);
      }

      // Update git config in the new worktree (best-effort)
      if (input.newBaseBranch) {
        try {
          const worktreeGit = simpleGit(updatedTask.worktree_path);
          await worktreeGit.addConfig('kangentic.baseBranch', input.newBaseBranch);
        } catch {
          // Non-fatal
        }
      }

      return tasks.getById(task.id)!;
    }

    if (task.worktree_path) {
      // --- Path A: Switch base branch (worktree exists) ---
      if (!fs.existsSync(task.worktree_path)) {
        throw new Error(`Worktree directory not found: ${task.worktree_path}`);
      }

      tasks.update({ id: task.id, base_branch: input.newBaseBranch || null });

      // Update git config in the worktree (best-effort)
      try {
        const worktreeGit = simpleGit(task.worktree_path);
        await worktreeGit.addConfig('kangentic.baseBranch', input.newBaseBranch);
      } catch {
        console.warn(`[TASK_SWITCH_BRANCH] Could not update git config in worktree`);
      }

      return tasks.getById(task.id)!;
    }

    // --- Path C: No worktree, no enableWorktree ---
    tasks.update({ id: task.id, base_branch: input.newBaseBranch || null });
    return tasks.getById(task.id)!;
  });
}
