import fs from 'node:fs';
import { ipcMain } from 'electron';
import { IPC } from '../../../shared/ipc-channels';
import { SessionRepository } from '../../db/repositories/session-repository';
import { WorktreeManager, isAutoGeneratedBranch } from '../../git/worktree-manager';
import { getProjectDb } from '../../db/database';
import {
  getProjectRepos,
  buildAutoCommandVars,
  ensureTaskWorktree,
  ensureTaskBranchCheckout,
  createTransitionEngine,
  cleanupTaskResources,
} from '../helpers';
import { guardActiveNonWorktreeSessions } from './task-move';
import type { IpcContext } from '../ipc-context';

export function registerTaskCrudHandlers(context: IpcContext): void {
  ipcMain.handle(IPC.TASK_LIST, (_, swimlaneId?) => {
    const { tasks } = getProjectRepos(context);
    return tasks.list(swimlaneId);
  });

  ipcMain.handle(IPC.TASK_CREATE, async (_, input) => {
    const { tasks, swimlanes, actions, attachments } = getProjectRepos(context);
    const { pendingAttachments, ...taskInput } = input;
    const task = tasks.create(taskInput);

    // Save any pending attachments from the dialog
    if (pendingAttachments?.length && context.currentProjectPath) {
      for (const att of pendingAttachments) {
        attachments.add(context.currentProjectPath, task.id, att.filename, att.data, att.media_type);
      }
    }

    // Auto-spawn: if target column has auto_spawn, start the agent
    const toLane = swimlanes.getById(task.swimlane_id);
    if (toLane?.auto_spawn && context.currentProjectPath && context.currentProjectId) {
      try {
        await ensureTaskWorktree(context, task, tasks, context.currentProjectPath);
      } catch (worktreeError) {
        console.error('[TASK_CREATE] Worktree creation failed:', worktreeError);
        return tasks.getById(task.id) ?? task;
      }

      // Checkout the task's branch in the main repo (non-worktree tasks only).
      // If checkout fails, the task is still created but no agent is spawned.
      try {
        guardActiveNonWorktreeSessions(context, task, tasks);
        await ensureTaskBranchCheckout(task, context.currentProjectPath);
      } catch (checkoutError) {
        console.error('[TASK_CREATE] Branch checkout failed:', checkoutError);
        return tasks.getById(task.id) ?? task;
      }

      const db = getProjectDb(context.currentProjectId);
      const sessionRepo = new SessionRepository(db);
      const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachments, context.currentProjectId, context.currentProjectPath);

      try {
        // Use '*' as fromSwimlaneId -- no source column on creation, matches wildcard transitions
        await engine.executeTransition(task, '*', toLane.id, toLane.permission_mode);
      } catch (err) {
        console.error('[TASK_CREATE] Transition engine error:', err);
      }

      // Re-read task; if still no session, resume suspended or spawn fresh
      let finalTask = tasks.getById(task.id);
      if (finalTask && !finalTask.session_id && toLane.auto_spawn) {
        console.log(`[TASK_CREATE] Ensuring agent for task ${task.id.slice(0, 8)}`);
        try {
          await engine.resumeSuspendedSession(finalTask, toLane.permission_mode);
          finalTask = tasks.getById(task.id);
        } catch (err) {
          console.error('[TASK_CREATE] Failed to start session:', err);
        }
      }

      // Schedule auto-command for freshly spawned session
      if (finalTask?.session_id && toLane.auto_command) {
        const vars = buildAutoCommandVars(finalTask);
        const interpolated = context.commandBuilder.interpolateTemplate(toLane.auto_command, vars);
        context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
      }
    }

    return tasks.getById(task.id) ?? task;
  });

  ipcMain.handle(IPC.TASK_UPDATE, async (_, input) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks } = getProjectRepos(context, resolvedProjectId);
    const existing = tasks.getById(input.id);

    // If title changed and task has a worktree branch, try to rename the branch
    if (input.title && existing?.branch_name && existing?.worktree_path
        && isAutoGeneratedBranch(existing.branch_name, existing.id, existing.title)
        && input.title !== existing.title && resolvedProjectPath
        && !existing.pr_url) {
      // Guard: skip if the agent is actively thinking (git operations may be in flight)
      const taskSession = context.sessionManager.listSessions()
        .find(s => s.taskId === input.id && (s.status === 'running' || s.status === 'queued'));
      const activityCache = context.sessionManager.getActivityCache();
      const isThinking = taskSession && activityCache[taskSession.id] === 'thinking';

      if (isThinking) {
        console.log(`[TASK_UPDATE] Skipping branch rename -- task ${input.id.slice(0, 8)} agent is thinking`);
      } else if (!fs.existsSync(existing.worktree_path)) {
        console.log(`[TASK_UPDATE] Skipping branch rename -- worktree path missing: ${existing.worktree_path}`);
      } else {
        const worktreeManager = new WorktreeManager(resolvedProjectPath);
        const newBranchName = await worktreeManager.withLock(() =>
          worktreeManager.renameBranch(input.id, existing.branch_name!, input.title),
        );
        if (newBranchName) {
          console.log(`[TASK_UPDATE] Branch renamed: ${existing.branch_name} -> ${newBranchName}`);
          input.branch_name = newBranchName;
        } else {
          console.log(`[TASK_UPDATE] Branch rename skipped (same slug or failed) for ${existing.branch_name}`);
        }
      }
    }

    return tasks.update(input);
  });

  ipcMain.handle(IPC.TASK_DELETE, async (_, id) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    const task = tasks.getById(id);
    if (task) {
      attachments.deleteByTaskId(id);
      await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
    }
    tasks.delete(id);
  });

  ipcMain.handle(IPC.TASK_LIST_ARCHIVED, () => {
    const { tasks } = getProjectRepos(context);
    return tasks.listArchived();
  });

  ipcMain.handle(IPC.TASK_UNARCHIVE, async (_, input: { id: string; targetSwimlaneId: string }) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    if (!resolvedProjectId) throw new Error('No project is currently open');

    const { tasks, swimlanes, actions, attachments: attachmentRepo } = getProjectRepos(context, resolvedProjectId);

    // Determine position at end of target lane
    const laneTasks = tasks.list(input.targetSwimlaneId);
    const position = laneTasks.length;

    const task = tasks.unarchive(input.id, input.targetSwimlaneId, position);

    const toLane = swimlanes.getById(input.targetSwimlaneId);

    // Guard: don't resume if target doesn't auto-spawn (backlog, done, or custom with auto_spawn=false)
    if (!toLane?.auto_spawn) {
      return tasks.getById(input.id);
    }

    // Create worktree if needed (any non-backlog column gets an agent)
    try {
      await ensureTaskWorktree(context, task, tasks, resolvedProjectPath);
    } catch (worktreeError) {
      console.error('[TASK_UNARCHIVE] Worktree creation failed:', worktreeError);
      return tasks.getById(input.id);
    }

    // Checkout the task's branch in the main repo (non-worktree tasks only).
    // If checkout fails, the task is still unarchived but no agent is spawned.
    try {
      guardActiveNonWorktreeSessions(context, task, tasks);
      await ensureTaskBranchCheckout(task, resolvedProjectPath);
    } catch (checkoutError) {
      console.error('[TASK_UNARCHIVE] Branch checkout failed:', checkoutError);
      return tasks.getById(input.id);
    }

    // Execute transition actions (from Done → target) for ALL non-kill columns
    if (resolvedProjectPath) {
      const doneLane = swimlanes.list().find((l) => l.role === 'done');
      if (doneLane) {
        const db = getProjectDb(resolvedProjectId);
        const sessionRepo = new SessionRepository(db);
        const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachmentRepo, resolvedProjectId, resolvedProjectPath);

        try {
          await engine.executeTransition(task, doneLane.id, input.targetSwimlaneId, toLane?.permission_mode, true);
        } catch (err) {
          console.error('[TASK_UNARCHIVE] Transition engine error:', err);
        }

        // Re-read task; if still no session, resume suspended or spawn fresh.
        let finalTask = tasks.getById(task.id);
        if (finalTask && !finalTask.session_id && toLane?.auto_spawn) {
          console.log(`[TASK_UNARCHIVE] Ensuring agent for task ${task.id.slice(0, 8)}`);
          try {
            await engine.resumeSuspendedSession(finalTask, toLane.permission_mode, true);
            finalTask = tasks.getById(task.id);
          } catch (err) {
            console.error('[TASK_UNARCHIVE] Failed to start session:', err);
          }
        }

        // Schedule auto-command for freshly spawned session
        if (finalTask?.session_id && toLane?.auto_command) {
          const vars = buildAutoCommandVars(finalTask);
          const interpolated = context.commandBuilder.interpolateTemplate(toLane.auto_command, vars);
          context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
        }
      }
    }

    return tasks.getById(input.id);
  });

  ipcMain.handle(IPC.TASK_BULK_DELETE, async (_, ids: string[]) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    const { tasks, attachments } = getProjectRepos(context, resolvedProjectId);
    for (const id of ids) {
      const task = tasks.getById(id);
      if (task) {
        attachments.deleteByTaskId(id);
        await cleanupTaskResources(context, task, tasks, resolvedProjectId, resolvedProjectPath);
      }
      tasks.delete(id);
    }
  });

  ipcMain.handle(IPC.TASK_BULK_UNARCHIVE, async (_, ids: string[], targetSwimlaneId: string) => {
    const resolvedProjectId = context.currentProjectId;
    const resolvedProjectPath = context.currentProjectPath;
    if (!resolvedProjectId) throw new Error('No project is currently open');

    const { tasks, swimlanes, actions, attachments: attachmentRepo } = getProjectRepos(context, resolvedProjectId);
    const toLane = swimlanes.getById(targetSwimlaneId);

    for (const id of ids) {
      const laneTasks = tasks.list(targetSwimlaneId);
      const position = laneTasks.length;
      const task = tasks.unarchive(id, targetSwimlaneId, position);

      if (!toLane?.auto_spawn) continue;

      try {
        await ensureTaskWorktree(context, task, tasks, resolvedProjectPath);
      } catch (worktreeError) {
        console.error(`[TASK_BULK_UNARCHIVE] Worktree creation failed for task ${id.slice(0, 8)}:`, worktreeError);
        continue;
      }

      // Checkout the task's branch in the main repo (non-worktree tasks only).
      // Catch per-task so one failure doesn't block the entire batch.
      try {
        guardActiveNonWorktreeSessions(context, task, tasks);
        await ensureTaskBranchCheckout(task, resolvedProjectPath);
      } catch (checkoutError) {
        console.error(`[TASK_BULK_UNARCHIVE] Branch checkout failed for task ${id.slice(0, 8)}:`, checkoutError);
        continue;
      }

      if (resolvedProjectPath) {
        const doneLane = swimlanes.list().find((lane) => lane.role === 'done');
        if (doneLane) {
          const db = getProjectDb(resolvedProjectId);
          const sessionRepo = new SessionRepository(db);
          const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachmentRepo, resolvedProjectId, resolvedProjectPath);

          try {
            await engine.executeTransition(task, doneLane.id, targetSwimlaneId, toLane?.permission_mode, true);
          } catch (error) {
            console.error('[TASK_BULK_UNARCHIVE] Transition engine error:', error);
          }

          let finalTask = tasks.getById(task.id);
          if (finalTask && !finalTask.session_id && toLane?.auto_spawn) {
            try {
              await engine.resumeSuspendedSession(finalTask, toLane.permission_mode, true);
              finalTask = tasks.getById(task.id);
            } catch (error) {
              console.error('[TASK_BULK_UNARCHIVE] Failed to start session:', error);
            }
          }

          if (finalTask?.session_id && toLane?.auto_command) {
            const vars = buildAutoCommandVars(finalTask);
            const interpolated = context.commandBuilder.interpolateTemplate(toLane.auto_command, vars);
            context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
          }
        }
      }
    }
  });
}
