import { execFileSync } from 'node:child_process';
import simpleGit, { SimpleGit } from 'simple-git';
import path from 'node:path';
import fs from 'node:fs';
import { slugify, computeSlugBudget, computeAutoBranchName } from '../../shared/slugify';

// ---------------------------------------------------------------------------
// Fetch throttle cache -- avoids redundant git fetch calls for the same
// project+branch within a short window. In-memory only (resets on restart).
// ---------------------------------------------------------------------------

const fetchCache = new Map<string, number>();

/** Skip fetch if the same project+branch was fetched within this window.
 *  Covers batch moves (5+ tasks dragged in quick succession) without
 *  significant staleness risk for spaced-out individual moves. */
const FETCH_THROTTLE_MS = 30 * 1000; // 30 seconds

/** Background prune debounce per project. */
const backgroundPruneTimestamps = new Map<string, number>();
const BACKGROUND_PRUNE_COOLDOWN_MS = 10 * 60 * 1000; // 10 minutes

/** Clear the fetch throttle cache (for testing). */
export function clearFetchCache(): void {
  fetchCache.clear();
}

function fetchCacheKey(projectPath: string, branch: string): string {
  const normalizedPath = process.platform === 'win32' ? projectPath.toLowerCase() : projectPath;
  return `${normalizedPath}:${branch}`;
}

/**
 * Fetch from origin if the branch hasn't been fetched recently.
 * Returns the start point to use (`origin/<branch>` or local `<branch>`).
 */
export async function fetchIfStale(
  git: SimpleGit,
  projectPath: string,
  branch: string,
): Promise<string> {
  const key = fetchCacheKey(projectPath, branch);
  const lastFetch = fetchCache.get(key);
  if (lastFetch && Date.now() - lastFetch < FETCH_THROTTLE_MS) {
    return `origin/${branch}`;
  }

  try {
    await git.raw(['fetch', 'origin', branch]);
    fetchCache.set(key, Date.now());
    return `origin/${branch}`;
  } catch {
    // No remote, branch not on remote, or network unavailable -- use local branch
    return branch;
  }
}

// ---------------------------------------------------------------------------
// Free functions -- lightweight checks, no simple-git dependency
// ---------------------------------------------------------------------------

/** Check whether the project path is inside a git repository. */
export function isGitRepo(projectPath: string): boolean {
  return fs.existsSync(path.join(projectPath, '.git'));
}

/** Check whether the project path is a git worktree (has `.git` as a file, not a directory). */
export function isInsideWorktree(projectPath: string): boolean {
  const dotGit = path.join(projectPath, '.git');
  try {
    return fs.statSync(dotGit).isFile();
  } catch {
    return false;
  }
}

/**
 * Check whether the project path IS a Kangentic-managed worktree checkout.
 *
 * A preview project's path looks like `<parent>/.kangentic/worktrees/<slug>`.
 * We check that the immediate parent dir is `worktrees` and its parent is
 * `.kangentic`. This avoids false positives when the app itself runs from
 * inside a worktree (e.g. the CWD contains `.kangentic/worktrees/` early
 * in the path, but the project isn't itself a preview worktree).
 */
export function isKangenticWorktree(projectPath: string): boolean {
  // Normalize all separators to forward slashes so the check works on any OS
  const normalized = projectPath.replace(/\\/g, '/');
  const segments = normalized.split('/').filter(Boolean);
  if (segments.length < 3) return false;
  const parentSegment = segments[segments.length - 2];
  const grandparentSegment = segments[segments.length - 3];
  return parentSegment === 'worktrees' && grandparentSegment === '.kangentic';
}

/** Check whether a file is tracked by git (committed or staged). */
export function isFileTracked(projectPath: string, filePath: string): boolean {
  try {
    execFileSync('git', ['ls-files', '--error-unmatch', '--', filePath], {
      cwd: projectPath, stdio: 'ignore',
    });
    return true;
  } catch {
    return false;
  }
}

/**
 * Check whether a branch name matches the auto-generated pattern for a task.
 * Auto-generated branches are `{slug}-{shortId}` where shortId is the first 8
 * chars of the task UUID. When the task was created off a non-default base
 * branch, the name is prefixed with the base as a namespace:
 * `{baseFlat}/{slug}-{shortId}`. The slug may have been truncated by the
 * dynamic path budget, so we check that the branch slug is a valid prefix of
 * the full slug. Custom branches set by the user will not match.
 */
export function isAutoGeneratedBranch(branchName: string, taskId: string, taskTitle: string): boolean {
  const shortId = taskId.slice(0, 8);
  const suffix = `-${shortId}`;
  if (!branchName.endsWith(suffix)) return false;

  const withoutSuffix = branchName.slice(0, -suffix.length);
  const firstSlashIndex = withoutSuffix.indexOf('/');
  const branchSlug = firstSlashIndex >= 0
    ? withoutSuffix.slice(firstSlashIndex + 1)
    : withoutSuffix;

  // Our auto-generated format has at most ONE slash (between the flattened
  // base-branch prefix and the task slug). User-supplied custom branches
  // with multiple segments (e.g. 'feature/bug/login') are rejected here.
  if (branchSlug.includes('/')) return false;

  if (branchSlug === 'task') return true; // fallback slug used when budget was 0
  const fullSlug = slugify(taskTitle) || 'task';
  return fullSlug.startsWith(branchSlug) && branchSlug.length > 0;
}

// ---------------------------------------------------------------------------
// node_modules junction / symlink
// ---------------------------------------------------------------------------

/** Check whether a path is a junction (Windows) by attempting readlink. */
function isJunction(targetPath: string): boolean {
  try {
    fs.readlinkSync(targetPath);
    return true;
  } catch {
    return false;
  }
}

/**
 * Remove a junction or symlink without following it into the target directory.
 *
 * On Windows, `fs.rmSync(junction, { recursive: true })` traverses the junction
 * and deletes the TARGET directory's contents (e.g. the main repo's node_modules).
 * This helper removes just the link itself using non-recursive rmSync.
 *
 * Exported so resource-cleanup can use it before recursive worktree removal.
 */
export function removeNodeModulesJunction(junctionPath: string): void {
  try {
    fs.lstatSync(junctionPath);
    // Check Windows junction FIRST - lstatSync().isSymbolicLink() can return
    // true for junctions on some Node.js/Windows versions, which would route
    // to rmSync (fails with EISDIR on directory reparse points). rmdirSync
    // calls RemoveDirectoryW which correctly removes the junction link.
    if (process.platform === 'win32' && isJunction(junctionPath)) {
      fs.rmdirSync(junctionPath);
    } else {
      // POSIX symlinks: rmSync works (they're file-like)
      fs.rmSync(junctionPath, { force: true });
    }
  } catch (error) {
    // ENOENT is expected (junction already gone)
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.warn(`[WORKTREE] Failed to remove junction ${junctionPath}: ${(error as Error).message}`);
    }
  }
}

/**
 * Create a filesystem junction (Windows) or symlink (Unix) from
 * `<worktree>/node_modules` to `<root>/node_modules` so the worktree gets
 * instant access to dependencies without running `npm install`.
 *
 * Non-fatal: logs a warning on failure but never throws.
 */
function linkNodeModules(worktreePath: string, rootPath: string): void {
  const rootModules = path.join(rootPath, 'node_modules');
  const worktreeModules = path.join(worktreePath, 'node_modules');

  // Not a Node project (or deps not installed yet). Skip silently.
  if (!fs.existsSync(rootModules)) return;

  try {
    const stat = fs.lstatSync(worktreeModules);
    const isLink = stat.isSymbolicLink()
      || (process.platform === 'win32' && stat.isDirectory() && isJunction(worktreeModules));

    if (isLink) {
      const target = fs.realpathSync(worktreeModules);
      const rootReal = fs.realpathSync(rootModules);
      if (target === rootReal) return; // Already correct
      // Points elsewhere. Remove just the link (not recursive - avoids
      // traversing into the target and deleting the main repo's modules).
      removeNodeModulesJunction(worktreeModules);
    } else {
      // Real directory (e.g. from a previous npm install). Remove it.
      fs.rmSync(worktreeModules, { recursive: true, force: true });
    }
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') {
      console.warn('[WORKTREE] Failed to check existing node_modules, will try to create link:', error);
    }
    // ENOENT means it doesn't exist yet. Will create below.
  }

  try {
    const linkType = process.platform === 'win32' ? 'junction' : 'dir';
    fs.symlinkSync(rootModules, worktreeModules, linkType);
    console.log(`[WORKTREE] Created node_modules ${linkType}: ${worktreeModules} -> ${rootModules}`);
  } catch (error) {
    console.warn('[WORKTREE] Failed to create node_modules link (non-fatal):', error);
  }
}

// ---------------------------------------------------------------------------
// Per-project serial queue for git-mutating operations
// ---------------------------------------------------------------------------

/**
 * Promise chain per project path. Each git-mutating call chains onto the
 * previous promise so operations execute in FIFO order. Different projects
 * run independently. This eliminates git lock contention that occurs when
 * multiple worktree operations hit the same .git directory concurrently.
 */
const projectQueues = new Map<string, Promise<unknown>>();

/** Normalize project path for use as a queue key (Windows is case-insensitive). */
function queueKey(projectPath: string): string {
  return process.platform === 'win32' ? projectPath.toLowerCase() : projectPath;
}

// ---------------------------------------------------------------------------
// WorktreeManager class
// ---------------------------------------------------------------------------

export class WorktreeManager {
  private git: SimpleGit;

  constructor(private projectPath: string, git?: SimpleGit) {
    this.git = git ?? simpleGit(projectPath);
  }

  /**
   * Serialize a git-mutating operation on this project's queue.
   * Operations on the same project execute in FIFO order; different
   * projects run independently.
   */
  withLock<T>(operation: () => Promise<T>): Promise<T> {
    return WorktreeManager.withGitLock(this.projectPath, operation);
  }

  /**
   * Serialize a git-mutating operation on the given project's queue.
   * A failed operation does not block subsequent ones.
   */
  static withGitLock<T>(projectPath: string, operation: () => Promise<T>): Promise<T> {
    const key = queueKey(projectPath);
    const previous = projectQueues.get(key) ?? Promise.resolve();
    const result = previous.then(operation, () => operation());
    // Store a caught version so unhandled rejections don't leak
    projectQueues.set(key, result.catch(() => {}));
    return result;
  }

  /** Remove the queue entry for a project (e.g. on project close/delete). */
  static clearQueue(projectPath: string): void {
    projectQueues.delete(queueKey(projectPath));
  }

  /**
   * Guard + create worktree in one call. Returns null if any guard fails
   * (already has worktree, worktrees disabled, not a git repo, is a worktree).
   */
  async ensureWorktree(
    task: { id: string; title: string; worktree_path: string | null; branch_name?: string | null; base_branch?: string | null; use_worktree?: number | null },
    gitConfig: { worktreesEnabled: boolean; defaultBaseBranch: string; copyFiles: string[] },
    options?: { onProgress?: (phase: string) => void; signal?: AbortSignal },
  ): Promise<{ worktreePath: string; branchName: string } | null> {
    if (task.worktree_path) return null;
    const shouldUseWorktree = task.use_worktree != null
      ? Boolean(task.use_worktree)
      : gitConfig.worktreesEnabled;
    if (!shouldUseWorktree) return null;
    if (!isGitRepo(this.projectPath)) return null;
    if (isInsideWorktree(this.projectPath)) return null;

    // Guard: git worktree add requires at least one commit. An unborn repo
    // (e.g. `git init` with no commits) has no valid HEAD ref, so the command
    // would fail with "fatal: not a valid object name". Skip worktrees and let
    // the agent run in the main repo directory instead.
    try {
      await this.git.raw(['rev-parse', 'HEAD']);
    } catch {
      console.log('[WORKTREE] Skipping worktree creation: repository has no commits yet');
      return null;
    }

    const defaultBaseBranch = gitConfig.defaultBaseBranch || 'main';
    const baseBranch = task.base_branch || defaultBaseBranch;
    return this.createWorktree(task.id, task.title, baseBranch, gitConfig.copyFiles, task.branch_name, { onProgress: options?.onProgress, signal: options?.signal, defaultBaseBranch });
  }

  /**
   * Create a worktree for a task. The worktree folder and branch are named
   * using a slug derived from the task title, with the taskId suffix to
   * guarantee uniqueness.
   *
   * Callers must wrap with `withLock()` to serialize concurrent operations
   * on the same project and prevent git lock contention.
   */
  async createWorktree(
    taskId: string,
    taskTitle: string,
    baseBranch: string = 'main',
    copyFiles: string[] = [],
    customBranchName?: string | null,
    options?: { onProgress?: (phase: string) => void; signal?: AbortSignal; defaultBaseBranch?: string },
  ): Promise<{ worktreePath: string; branchName: string }> {
    const shortId = taskId.slice(0, 8);
    const defaultBaseBranch = options?.defaultBaseBranch ?? 'main';
    let branchName: string;
    let folderName: string;

    // On Windows, dynamically compute slug length to stay under MAX_PATH (260).
    // On other platforms, use the static default (20 chars).
    const slugBudget = process.platform === 'win32'
      ? computeSlugBudget(this.projectPath)
      : 20;

    if (customBranchName) {
      branchName = customBranchName;
      // Slugify the custom name for the folder (replace / with -)
      const slugifiedCustom = slugify(customBranchName.replace(/\//g, '-'), slugBudget);
      folderName = `${slugifiedCustom || 'task'}-${shortId}`;
    } else {
      const slug = slugify(taskTitle, slugBudget) || 'task';
      folderName = `${slug}-${shortId}`;
      // Branch name may include a base-branch namespace prefix when branching
      // off a non-default base; folder name intentionally stays flat.
      branchName = computeAutoBranchName(baseBranch, defaultBaseBranch, slug, shortId);
    }

    const worktreePath = path.join(this.projectPath, '.kangentic', 'worktrees', folderName);

    // Ensure worktrees dir exists
    const worktreesDir = path.join(this.projectPath, '.kangentic', 'worktrees');
    try {
      fs.mkdirSync(worktreesDir, { recursive: true });
    } catch (err) {
      console.error(`[WORKTREE] Failed to create worktrees directory: ${worktreesDir}`, err);
      throw new Error(`Cannot create worktrees directory at ${worktreesDir}: ${(err as Error).message}`);
    }

    // Fetch the latest from origin so worktrees start from up-to-date code.
    // Uses throttle cache to skip redundant fetches within a 5-minute window.
    const startPoint = await fetchIfStale(this.git, this.projectPath, baseBranch);
    options?.onProgress?.('creating-worktree');
    options?.signal?.throwIfAborted();

    // Check if the branch already exists (stale branch from failed cleanup,
    // or pre-existing custom branch)
    let branchExists = false;
    try {
      await this.git.raw(['rev-parse', '--verify', branchName]);
      branchExists = true;
    } catch {
      // Branch does not exist -- will create it
    }
    options?.signal?.throwIfAborted();

    // Create worktree: attach to existing branch or create a new one.
    // Callers must wrap with withLock() to serialize concurrent operations.
    // Use full removeWorktree (git worktree remove --force + EPERM retries)
    // instead of a single rmSync. On Windows, file handles from a recently
    // killed PTY may still be held, and rmSync fails with EPERM.
    if (fs.existsSync(worktreePath)) {
      const removed = await this.removeWorktree(worktreePath);
      if (!removed) {
        throw new Error(`Cannot create worktree: stale directory at ${worktreePath} could not be removed. A process may still hold file handles. Close any terminals or editors using this path and retry.`);
      }
      options?.signal?.throwIfAborted();
    }
    // On Windows, enable long paths to prevent "Filename too long" errors
    // when the project contains deeply nested files (e.g. .NET migrations).
    // The -c flag is per-command and does not modify the project's git config.
    // This setting is Windows-only (uses \\?\ extended-length path prefix);
    // macOS/Linux have 1024-4096 byte PATH_MAX and are unaffected.
    const longPathsConfig = process.platform === 'win32' ? ['-c', 'core.longpaths=true'] : [];
    if (branchExists) {
      await this.git.raw([...longPathsConfig, 'worktree', 'add', worktreePath, branchName]);
      console.log(`[WORKTREE] Created worktree (existing branch): ${branchName}`);
    } else {
      await this.git.raw([...longPathsConfig, 'worktree', 'add', '-b', branchName, worktreePath, startPoint]);
      console.log(`[WORKTREE] Created worktree (new branch): ${branchName} from ${startPoint}`);
    }

    // Post-creation configuration: git config writes and sparse-checkout run
    // in parallel since they operate on independent parts of the worktree's
    // .git state. File copies and node_modules linking stay sequential after.
    const wtGit = simpleGit(worktreePath);
    await Promise.all([
      // Store the base branch in git config so agents can read it via
      // `git config kangentic.baseBranch` without accessing files outside the worktree.
      wtGit.raw(['config', 'kangentic.baseBranch', baseBranch]).catch(() => {
        // Non-fatal -- merge-back falls back to 'main'
      }),
      // Persist long paths in the worktree's local config (Windows only)
      process.platform === 'win32'
        ? wtGit.raw(['config', 'core.longpaths', 'true']).catch(() => { /* non-fatal */ })
        : Promise.resolve(),
      // Exclude .claude/commands/ from worktree via sparse-checkout.
      // Commands walk up the directory tree from worktree CWD to the main repo's
      // .claude/commands/, so excluding them prevents duplicate discovery.
      // Requires git 2.25+; older versions skip gracefully.
      // The two sparse-checkout commands are sequential (init then set).
      (async () => {
        try {
          await wtGit.raw(['sparse-checkout', 'init', '--no-cone']);
          await wtGit.raw(['sparse-checkout', 'set', '/*', '!/.claude/commands/']);
        } catch (sparseError) {
          console.warn('[WORKTREE] Sparse-checkout not available (requires git 2.25+), skipping:', sparseError);
        }
      })(),
    ]);

    // Copy specified files into the worktree (skip .claude/ entries --
    // sparse-checkout keeps .claude/ but excludes commands/,
    // and hooks are delivered via --settings flag pointing to session directory)
    for (const file of copyFiles) {
      if (file.startsWith('.claude/') || file.startsWith('.claude\\')) continue;
      const src = path.join(this.projectPath, file);
      const dest = path.join(worktreePath, file);
      if (fs.existsSync(src)) {
        fs.mkdirSync(path.dirname(dest), { recursive: true });
        fs.copyFileSync(src, dest);
      }
    }

    // Link node_modules from root so worktree agents can run typecheck/test
    // without a slow npm install. Non-fatal if it fails.
    linkNodeModules(worktreePath, this.projectPath);

    return { worktreePath, branchName };
  }

  /**
   * Rename the git branch for a task after a title edit.
   * Only renames the branch ref -- the worktree directory stays unchanged.
   * Returns the new branch name on success, null if skipped or failed.
   */
  async renameBranch(
    taskId: string,
    oldBranchName: string,
    newTitle: string,
    options?: { baseBranch?: string | null; defaultBaseBranch?: string },
  ): Promise<string | null> {
    const slugBudget = process.platform === 'win32'
      ? computeSlugBudget(this.projectPath)
      : 20;
    const slug = slugify(newTitle, slugBudget) || 'task';
    const shortId = taskId.slice(0, 8);
    const baseBranch = options?.baseBranch ?? '';
    const defaultBaseBranch = options?.defaultBaseBranch ?? 'main';
    const newBranchName = computeAutoBranchName(baseBranch, defaultBaseBranch, slug, shortId);

    if (newBranchName === oldBranchName) return null; // slug didn't change

    try {
      await this.git.raw(['branch', '-m', oldBranchName, newBranchName]);
      return newBranchName;
    } catch (err) {
      console.error('[WORKTREE] Branch rename failed:', err);
      return null;
    }
  }

  async removeWorktree(worktreePath: string): Promise<boolean> {
    if (!fs.existsSync(worktreePath)) return true;

    // Remove node_modules junction BEFORE any recursive operation to prevent
    // git worktree remove (or rmSync) from traversing the junction and
    // deleting the main repo's node_modules.
    removeNodeModulesJunction(path.join(worktreePath, 'node_modules'));

    try {
      await this.git.raw(['worktree', 'remove', worktreePath, '--force']);
      return true;
    } catch (error) {
      console.log(`[WORKTREE] git worktree remove failed, falling back to manual removal: ${(error as Error).message}`);
    }

    // Callers should have awaited process exit before calling removeWorktree,
    // so handles should be released. Single attempt + one short NTFS flush
    // retry (500ms) as a safety net.
    const delays = [0, 500];
    for (const delay of delays) {
      if (delay > 0) {
        await new Promise(resolve => setTimeout(resolve, delay));
      }
      try {
        fs.rmSync(worktreePath, { recursive: true, force: true });
        await this.git.raw(['worktree', 'prune']);
        return true;
      } catch (error) {
        console.log(`[WORKTREE] rmSync retry failed (waited ${delay}ms): ${(error as Error).message}`);
      }
    }

    // Both attempts exhausted - prune what we can, log the stale path
    try { await this.git.raw(['worktree', 'prune']); } catch { /* best effort */ }
    console.warn(`[WorktreeManager] Could not remove worktree after retries: ${worktreePath}`);
    return false;
  }

  async removeBranch(branchName: string): Promise<void> {
    try {
      await this.git.raw(['branch', '-D', branchName]);
    } catch { /* branch may not exist */ }
  }

  /**
   * List remote branches sorted by most recent commit first.
   * Fetches from origin first (fails silently if offline).
   */
  async listRemoteBranches(): Promise<string[]> {
    try { await this.git.raw(['fetch', '--prune']); } catch { /* offline OK */ }
    // %(refname:short) shortens origin/HEAD to bare "origin" -- filter by
    // requiring the origin/ prefix before stripping it, which excludes both
    // the HEAD symref and any non-origin remotes.
    const raw = await this.git.raw(['branch', '-r', '--sort=-committerdate', '--format=%(refname:short)']);
    const seen = new Set<string>();
    return raw.split('\n')
      .map(l => l.trim())
      .filter(l => l.startsWith('origin/') && !l.endsWith('/HEAD'))
      .map(l => l.slice('origin/'.length))
      .filter(l => {
        if (!l || seen.has(l)) return false;
        seen.add(l);
        return true;
      });
  }

  /**
   * Checkout a branch in the main repo for non-worktree tasks.
   * Throws if the working tree is dirty or the branch doesn't exist.
   */
  async checkoutBranch(branchName: string): Promise<void> {
    const currentBranch = (await this.git.revparse(['--abbrev-ref', 'HEAD'])).trim();
    if (currentBranch === branchName) return;

    const status = await this.git.status();
    const trackedChanges = status.files.filter(
      file => file.index !== '?' && file.working_dir !== '?',
    );
    if (trackedChanges.length > 0) {
      throw new Error(
        `Cannot switch to branch '${branchName}': you have uncommitted changes. `
        + `Commit or stash your changes, or enable worktree mode for this task.`
      );
    }

    await this.git.checkout(branchName);
  }

  async pruneWorktrees(): Promise<void> {
    await this.git.raw(['worktree', 'prune']);
  }

  /**
   * Schedule a background prune for this project. Debounced per-project
   * (at most once per 10 minutes). Acquires the git lock to avoid
   * contention with concurrent worktree operations. Never throws.
   */
  static scheduleBackgroundPrune(projectPath: string): void {
    const key = process.platform === 'win32' ? projectPath.toLowerCase() : projectPath;
    const lastPrune = backgroundPruneTimestamps.get(key);
    if (lastPrune && Date.now() - lastPrune < BACKGROUND_PRUNE_COOLDOWN_MS) return;
    backgroundPruneTimestamps.set(key, Date.now());

    WorktreeManager.withGitLock(projectPath, async () => {
      const git = simpleGit(projectPath);
      await git.raw(['worktree', 'prune']);
      console.log(`[WORKTREE] Background prune completed for ${projectPath}`);
    }).catch((error) => {
      console.warn(`[WORKTREE] Background prune failed (non-fatal): ${(error as Error).message}`);
    });
  }

  async listWorktrees(): Promise<string[]> {
    const result = await this.git.raw(['worktree', 'list', '--porcelain']);
    const worktrees: string[] = [];
    for (const line of result.split('\n')) {
      if (line.startsWith('worktree ')) {
        worktrees.push(line.replace('worktree ', ''));
      }
    }
    return worktrees;
  }

}
