import fs from 'node:fs';
import path from 'node:path';
import simpleGit from 'simple-git';
import { TaskRepository } from '../db/repositories/task-repository';
import { SwimlaneRepository } from '../db/repositories/swimlane-repository';
import { ActionRepository } from '../db/repositories/action-repository';
import { AttachmentRepository } from '../db/repositories/attachment-repository';
import { SessionRepository } from '../db/repositories/session-repository';
import { TransitionEngine } from '../engine/transition-engine';
import { WorktreeManager, isGitRepo, isFileTracked, isAutoGeneratedBranch } from '../git/worktree-manager';
import { getProjectDb } from '../db/database';
import type { Task } from '../../shared/types';
import type { IpcContext } from './ipc-context';

/**
 * Ensure `.kangentic/` and `.claude/settings.local.json` are listed in the
 * project's `.gitignore`.  Fully wrapped in try-catch -- a read-only project
 * directory or permission issue must never prevent the app from opening.
 */
export function ensureGitignore(projectPath: string): void {
  if (!isGitRepo(projectPath)) return;
  try {
    const gitignorePath = path.join(projectPath, '.gitignore');
    let content = '';
    try {
      content = fs.readFileSync(gitignorePath, 'utf-8');
    } catch {
      // No .gitignore yet -- we'll create one
    }

    // 1. Ensure .kangentic/ is ignored
    const lines = content.split('\n');
    const kangenticIgnored = lines.some(
      (l) => l.trim() === '.kangentic' || l.trim() === '.kangentic/',
    );
    if (!kangenticIgnored) {
      const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
      content = content + separator + '.kangentic/\n';
      fs.writeFileSync(gitignorePath, content);
    }

    // 2. Ensure .claude/settings.local.json is ignored -- but only if the project
    //    hasn't intentionally committed it (e.g. to accumulate permission allowlists).
    const linesAfter = content.split('\n');
    const settingsIgnored = linesAfter.some(
      (l) => l.trim() === '.claude/settings.local.json',
    );
    if (!settingsIgnored) {
      const settingsTracked = isFileTracked(projectPath, '.claude/settings.local.json');
      if (!settingsTracked) {
        const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
        content = content + separator + '.claude/settings.local.json\n';
        fs.writeFileSync(gitignorePath, content);
      }
    }

    // 3. Ensure kangentic.local.json is ignored (personal board overrides)
    const linesAfterLocal = content.split('\n');
    const localConfigIgnored = linesAfterLocal.some(
      (l) => l.trim() === 'kangentic.local.json',
    );
    if (!localConfigIgnored) {
      const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
      fs.writeFileSync(gitignorePath, content + separator + 'kangentic.local.json\n');
    }
  } catch (err) {
    // Non-fatal: log and continue. Project may be read-only or on a network drive.
    console.warn(`[PROJECT_OPEN] Could not update .gitignore at ${projectPath}:`, err);
  }
}

/** Build template variables for auto-command interpolation. */
export function buildAutoCommandVars(task: Task): Record<string, string> {
  return {
    title: task.title,
    description: task.description,
    taskId: task.id,
    worktreePath: task.worktree_path || '',
    branchName: task.branch_name || '',
  };
}

/**
 * Create a worktree for a task if needed and update the DB + task object in place.
 * No-ops when worktrees are disabled or project isn't a git repo.
 * Throws on worktree creation failure (e.g. duplicate branch).
 */
export async function ensureTaskWorktree(context: IpcContext, task: Task, tasks: TaskRepository, projectPath?: string | null, options?: { signal?: AbortSignal }): Promise<void> {
  options?.signal?.throwIfAborted();
  const resolvedProjectPath = projectPath ?? context.currentProjectPath;
  if (!resolvedProjectPath) return;
  const config = context.configManager.getEffectiveConfig(resolvedProjectPath);
  const worktreeManager = new WorktreeManager(resolvedProjectPath);
  const result = await worktreeManager.withLock(() => worktreeManager.ensureWorktree(task, config.git));
  if (result) {
    tasks.update({ id: task.id, worktree_path: result.worktreePath, branch_name: result.branchName });
    Object.assign(task, tasks.getById(task.id));
  }
}

/**
 * Checkout the task's branch in the main repo for non-worktree tasks.
 *
 * Custom branch names (not matching the auto-generated pattern) are fetched
 * from origin, created from base_branch or remote if needed, then checked out.
 * Auto-generated branches fall through to the base_branch checkout path.
 *
 * No-ops when: no project path, task uses a worktree, not a git repo,
 * or task has neither a custom branch_name nor a base_branch.
 * Throws on dirty repo or checkout failure so the caller can block agent spawn.
 */
export async function ensureTaskBranchCheckout(
  task: Task,
  projectPath?: string | null,
  options?: { signal?: AbortSignal },
): Promise<void> {
  options?.signal?.throwIfAborted();
  if (!projectPath) return;
  if (task.worktree_path) return;
  if (!isGitRepo(projectPath)) return;

  // Custom branch name: fetch latest, create if needed, then checkout
  if (task.branch_name && !isAutoGeneratedBranch(task.branch_name, task.id, task.title)) {
    await WorktreeManager.withGitLock(projectPath, async () => {
      const git = simpleGit(projectPath);

      // Always fetch latest from origin (best-effort, fails silently if offline)
      try {
        await git.raw(['fetch', 'origin', task.branch_name!]);
      } catch {
        // Offline, no remote, or branch not on remote
      }

      // Check if branch exists locally (user's local may be ahead of remote, that's fine)
      let branchExists = false;
      try {
        await git.raw(['rev-parse', '--verify', task.branch_name!]);
        branchExists = true;
      } catch {
        // Branch does not exist locally
      }

      if (!branchExists) {
        // Check if it exists on remote (we already fetched above)
        let existsOnRemote = false;
        try {
          await git.raw(['rev-parse', '--verify', `origin/${task.branch_name}`]);
          existsOnRemote = true;
        } catch {
          // Not on remote either
        }

        if (existsOnRemote) {
          // Create local branch tracking the remote
          await git.raw(['branch', task.branch_name!, `origin/${task.branch_name}`]);
        } else {
          // Branch doesn't exist anywhere. Create from base_branch.
          const baseBranch = task.base_branch || 'main';
          await git.raw(['branch', task.branch_name!, baseBranch]);
        }
      }

      const worktreeManager = new WorktreeManager(projectPath);
      await worktreeManager.checkoutBranch(task.branch_name!);
    });
    return;
  }

  // Fall through to existing base_branch checkout logic
  if (!task.base_branch) return;

  const worktreeManager = new WorktreeManager(projectPath);
  await worktreeManager.withLock(() => worktreeManager.checkoutBranch(task.base_branch!));
}

/** Create a TransitionEngine wired to explicit project context (not singletons). */
export function createTransitionEngine(
  context: IpcContext,
  actions: ActionRepository,
  tasks: TaskRepository,
  sessionRepo: SessionRepository,
  attachments: AttachmentRepository,
  projectId: string,
  projectPath: string | null,
): TransitionEngine {
  return new TransitionEngine(
    context.sessionManager, actions, tasks, context.claudeDetector, context.commandBuilder,
    () => {
      const config = context.configManager.getEffectiveConfig(projectPath || undefined);
      const gitConfig = { ...config.git };
      // Overlay board config's defaultBaseBranch (team-shared) onto gitConfig
      const boardDefaultBranch = context.boardConfigManager.getDefaultBaseBranch();
      if (boardDefaultBranch) {
        gitConfig.defaultBaseBranch = boardDefaultBranch;
      }
      return {
        permissionMode: config.claude.permissionMode,
        claudePath: config.claude.cliPath,
        projectPath,
        projectId,
        gitConfig,
        mcpServerEnabled: config.mcpServer?.enabled ?? true,
      };
    },
    sessionRepo,
    attachments,
  );
}

export function getProjectRepos(context: IpcContext, projectId?: string | null): { tasks: TaskRepository; swimlanes: SwimlaneRepository; actions: ActionRepository; attachments: AttachmentRepository } {
  const resolvedProjectId = projectId ?? context.currentProjectId;
  if (!resolvedProjectId) throw new Error('No project is currently open');
  const db = getProjectDb(resolvedProjectId);
  return {
    tasks: new TaskRepository(db),
    swimlanes: new SwimlaneRepository(db),
    actions: new ActionRepository(db),
    attachments: new AttachmentRepository(db),
  };
}

/**
 * Auto-spawn an agent session for a newly created task when the target
 * swimlane has `auto_spawn` enabled. Handles worktree setup, branch checkout,
 * transition engine execution, session resume fallback, and auto-command
 * injection.
 *
 * Called from both the SessionManager `task-created` event (internal MCP
 * bridge) and the external CommandBridge `onTaskCreated` callback.
 */
export async function autoSpawnForTask(
  context: IpcContext,
  projectId: string,
  task: { id: string; title: string },
  swimlaneId: string,
): Promise<void> {
  try {
    const db = getProjectDb(projectId);
    const swimlaneRepo = new SwimlaneRepository(db);
    const toLane = swimlaneRepo.getById(swimlaneId);
    if (!toLane?.auto_spawn) return;

    const project = context.projectRepo.getById(projectId);
    const projectPath = project?.path ?? null;
    if (!projectPath) return;

    const { tasks, actions, attachments } = getProjectRepos(context, projectId);
    const fullTask = tasks.getById(task.id);
    if (!fullTask) return;

    try {
      await ensureTaskWorktree(context, fullTask, tasks, projectPath);
    } catch (worktreeError) {
      console.error('[MCP auto-spawn] Worktree creation failed:', worktreeError);
      return;
    }

    // Checkout branch for non-worktree tasks (may fail if another session is active)
    if (fullTask.base_branch && !fullTask.worktree_path) {
      try {
        // Inlined from guardActiveNonWorktreeSessions to avoid circular import with task-move.ts
        const activeSessions = context.sessionManager.listSessions()
          .filter(session => session.taskId !== fullTask.id && (session.status === 'running' || session.status === 'queued'));
        const otherNonWorktreeSessions = activeSessions.filter(session => {
          const otherTask = tasks.getById(session.taskId);
          return otherTask && !otherTask.worktree_path;
        });
        if (otherNonWorktreeSessions.length > 0) {
          throw new Error(
            `Cannot switch to branch '${fullTask.base_branch}': another task is running in the main repo. `
            + `Enable worktree mode for branch isolation.`
          );
        }
        await ensureTaskBranchCheckout(fullTask, projectPath);
      } catch (checkoutError) {
        console.error('[MCP auto-spawn] Branch checkout failed:', checkoutError);
        return;
      }
    }

    const sessionRepo = new SessionRepository(db);
    const engine = createTransitionEngine(context, actions, tasks, sessionRepo, attachments, projectId, projectPath);

    try {
      await engine.executeTransition(fullTask, '*', toLane.id, toLane.permission_mode);
    } catch (err) {
      console.error('[MCP auto-spawn] Transition engine error:', err);
    }

    // Re-read task; if still no session, resume suspended or spawn fresh
    let finalTask = tasks.getById(task.id);
    if (finalTask && !finalTask.session_id && toLane.auto_spawn) {
      try {
        await engine.resumeSuspendedSession(finalTask, toLane.permission_mode);
        finalTask = tasks.getById(task.id);
      } catch (err) {
        console.error('[MCP auto-spawn] Failed to start session:', err);
      }
    }

    // Schedule auto-command for freshly spawned session
    if (finalTask?.session_id && toLane.auto_command) {
      const vars = buildAutoCommandVars(finalTask);
      const interpolated = context.commandBuilder.interpolateTemplate(toLane.auto_command, vars);
      context.commandInjector.schedule(finalTask.id, finalTask.session_id, interpolated, { freshlySpawned: true });
    }

    console.log(`[MCP auto-spawn] Spawned agent for "${task.title}" in ${toLane.name}`);
  } catch (err) {
    console.error('[MCP auto-spawn] Failed:', err);
  }
}

/**
 * Kill the PTY session and wipe session records for a task.
 * Preserves the worktree and branch so code is not lost.
 *
 * Used by TASK_MOVE → Backlog ("shelve this task").
 */
export async function cleanupTaskSession(
  context: IpcContext,
  task: { id: string; session_id: string | null; worktree_path: string | null; branch_name: string | null },
  tasks: TaskRepository,
  projectId?: string | null,
  projectPath?: string | null,
): Promise<void> {
  const resolvedProjectId = projectId ?? context.currentProjectId;
  const resolvedProjectPath = projectPath ?? context.currentProjectPath;

  // Kill active PTY session and wait for process exit before proceeding.
  // The PTY process holds CWD + conpty handles on the worktree directory;
  // awaiting exit ensures those handles are released before cleanup.
  if (task.session_id) {
    try {
      context.sessionManager.kill(task.session_id);
      await context.sessionManager.awaitExit(task.session_id);
      context.sessionManager.remove(task.session_id);
    } catch { /* may already be dead */ }
    tasks.update({ id: task.id, session_id: null });
  }

  // Safety net: kill any PTY session for this task that was spawned by a
  // concurrent move but not yet written to the task's session_id field.
  context.sessionManager.removeByTaskId(task.id);

  // Remove session DB records + directories from disk
  if (resolvedProjectId) {
    const db = getProjectDb(resolvedProjectId);
    const sessionRepo = new SessionRepository(db);

    // Best-effort disk cleanup (non-fatal -- DB records are the source of truth)
    if (resolvedProjectPath) {
      const records = db.prepare(
        'SELECT claude_session_id FROM sessions WHERE task_id = ? AND claude_session_id IS NOT NULL'
      ).all(task.id) as Array<{ claude_session_id: string }>;
      for (const { claude_session_id } of records) {
        const sessionDir = path.join(resolvedProjectPath, '.kangentic', 'sessions', claude_session_id);
        try { fs.rmSync(sessionDir, { recursive: true, force: true }); } catch { /* may not exist */ }
      }
    }

    // Always delete DB records -- this must succeed for task DELETE to pass FK check
    sessionRepo.deleteByTaskId(task.id);
  }
}

/**
 * Full cleanup: kill session, remove worktree + branch, wipe session records.
 *
 * Used by TASK_DELETE (permanent removal) and TASK_MOVE → Backlog (full reset).
 */
export async function cleanupTaskResources(
  context: IpcContext,
  task: { id: string; session_id: string | null; worktree_path: string | null; branch_name: string | null },
  tasks: TaskRepository,
  projectId?: string | null,
  projectPath?: string | null,
): Promise<void> {
  await cleanupTaskSession(context, task, tasks, projectId, projectPath);

  const resolvedProjectPath = projectPath ?? context.currentProjectPath;

  // Remove worktree + branch
  if (task.worktree_path && resolvedProjectPath) {
    let removed = false;
    try {
      const worktreeManager = new WorktreeManager(resolvedProjectPath);
      await worktreeManager.withLock(async () => {
        removed = await worktreeManager.removeWorktree(task.worktree_path!);
        if (removed && task.branch_name) {
          const config = context.configManager.getEffectiveConfig(resolvedProjectPath);
          if (config.git.autoCleanup) {
            // Prune stale worktree metadata so git allows branch deletion
            // even if removeWorktree couldn't fully remove the directory
            try { await worktreeManager.pruneWorktrees(); } catch { /* best effort */ }
            await worktreeManager.removeBranch(task.branch_name);
          }
        }
      });
    } catch (err) {
      console.error(`[WORKTREE] Failed to clean up worktree for task ${task.id.slice(0, 8)}:`, err);
    }
    // Only clear DB fields if the directory was actually removed.
    // Keeping them set allows resource-cleanup to retry on next startup.
    if (removed) {
      tasks.update({ id: task.id, worktree_path: null, branch_name: null });
    }
  }
}
