/**
 * Unit tests for auto-generated worktree branch naming.
 *
 * Covers the prefix-namespace scheme that encodes a non-default base branch
 * into the generated branch name so agents and reviewers can tell at a glance
 * which base a worktree was cut from.
 */
import { describe, it, expect } from 'vitest';
import { computeAutoBranchName } from '../../src/shared/slugify';
import { isAutoGeneratedBranch } from '../../src/main/git/worktree-manager';

describe('computeAutoBranchName', () => {
  it('returns legacy unprefixed form when base equals default', () => {
    expect(computeAutoBranchName('main', 'main', 'task-title', 'ab12cd34'))
      .toBe('task-title-ab12cd34');
  });

  it('returns legacy unprefixed form when base is empty', () => {
    expect(computeAutoBranchName('', 'main', 'task-title', 'ab12cd34'))
      .toBe('task-title-ab12cd34');
  });

  it('prefixes with flat base name for non-default simple base', () => {
    expect(computeAutoBranchName('staging', 'main', 'task-title', 'ab12cd34'))
      .toBe('staging/task-title-ab12cd34');
  });

  it('flattens slashes in the base so the ref does not collide with an existing branch', () => {
    expect(computeAutoBranchName('bugfix/inacc-adjustments', 'main', 'task-title', 'ab12cd34'))
      .toBe('bugfix-inacc-adjustments/task-title-ab12cd34');
  });

  it('flattens multiple slash levels', () => {
    expect(computeAutoBranchName('release/q2/2026', 'main', 'task-title', 'ab12cd34'))
      .toBe('release-q2-2026/task-title-ab12cd34');
  });

  it('trims whitespace before comparing to default', () => {
    expect(computeAutoBranchName('  main  ', 'main', 'task-title', 'ab12cd34'))
      .toBe('task-title-ab12cd34');
  });
});

describe('isAutoGeneratedBranch -- prefixed namespace support', () => {
  const taskId = 'ab12cd34-5678-90ab-cdef-111122223333';
  const title = 'Fix login bug';

  it('matches legacy unprefixed branches (backward compat)', () => {
    expect(isAutoGeneratedBranch('fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches the fallback "task" slug', () => {
    expect(isAutoGeneratedBranch('task-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches prefixed branches cut from a non-default base', () => {
    expect(isAutoGeneratedBranch('staging/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches prefixed branches where the base had slashes (flattened)', () => {
    expect(isAutoGeneratedBranch('bugfix-inacc-adjustments/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches prefixed branches whose base contains dots (e.g. release/v2.0)', () => {
    // Flattened base 'release-v2.0' contains '.' - must still be recognized
    // so title-edit rename works on tasks cut from version-tagged base branches.
    expect(isAutoGeneratedBranch('release-v2.0/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches prefixed branches whose base contains underscores', () => {
    expect(isAutoGeneratedBranch('feature_x/fix-login-bug-ab12cd34', taskId, title)).toBe(true);
  });

  it('matches truncated slugs (dynamic MAX_PATH budget)', () => {
    expect(isAutoGeneratedBranch('staging/fix-login-ab12cd34', taskId, title)).toBe(true);
  });

  it('does not match user-supplied custom branches that look nothing like the slug', () => {
    expect(isAutoGeneratedBranch('feature/something-else-ab12cd34', taskId, title)).toBe(false);
  });

  it('does not match branches with the wrong shortId suffix', () => {
    expect(isAutoGeneratedBranch('fix-login-bug-99999999', taskId, title)).toBe(false);
  });

  it('does not match branches whose prefix contains invalid characters (e.g. user custom with slashes)', () => {
    // 'feature/sub.path' has a '.' which isn't in our flattened-base charset,
    // so we treat it as a user custom name and refuse to rename.
    expect(isAutoGeneratedBranch('feature/sub.path/fix-login-bug-ab12cd34', taskId, title)).toBe(false);
  });
});
